# flake.module.nix — project-specific flake-parts customizations.
#
# seihou does NOT manage this file: it is never regenerated or overwritten by
# `seihou run` or module migrations, so it is the conflict-free home for every
# customization that must survive nix-haskell-flake template upgrades. See
# flake.module.nix.example (generated by the module) for the full option list.
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ REQUIRED: this file MUST be git-tracked (`git add flake.module.nix`).      │
# │ Nix flakes evaluate only files tracked by git, so flake.nix's              │
# │ `builtins.pathExists ./flake.module.nix` import guard sees an untracked    │
# │ file as ABSENT and silently ignores everything below.                      │
# └──────────────────────────────────────────────────────────────────────────┘
{ inputs, ... }:
{
  perSystem = { pkgs, config, ... }:
    let
      # okf builds its package set from nixpkgs' ghc9124 with the shared
      # haskell-nix patch registry (mori://shinzui/haskell-nix) composed on top.
      # nix.haskell-nix = true makes the module own the rev-pinned
      # inputs.haskell-nix; its haskellExtension supplies every version-scoped
      # patch okf needs — streamly, streamly-core, unicode-data, openai, cradle,
      # and the whole baikai family (baikai / baikai-claude / baikai-kit /
      # baikai-openai at the pinned baikai-src rev) — so none of them are hand
      # pinned here any more.
      #
      # The extension also disables library profiling and Haddock across the
      # whole set (it overrides mkDerivation, so okf-core/okf-cli inherit it via
      # callCabal2nix). That replaces okf's former `fleetBuildSettings`: nothing
      # here reads the `p_` way or the `doc` output, and
      # `haskell.packages.ghc9124.*` is absent from cache.nixos.org, so every
      # consumer would otherwise compile both twice from source. Profiling is
      # contagious across a dependency edge, so it is flipped whole-scope rather
      # than per package; `haskell.lib.compose.{doHaddock,enableLibraryProfiling}`
      # still re-apply on top for a single package.
      haskellPackages = pkgs.haskell.packages.ghc9124.override {
        overrides =
          inputs.haskell-nix.lib.haskellExtension pkgs.haskell.lib.compose pkgs;
      };

      # okf is a multi-package project: okf-core (library) and okf-cli (library +
      # `okf` executable, depends on okf-core). There is no root .cabal file, so
      # callCabal2nix is pointed at each package directory and okf-cli is given
      # okf-core as its inter-package dependency. nix.builtin-package = false, so
      # the seihou-managed nix/haskell.nix emits no packages.default to collide
      # with these definitions.

      # 7-char git SHA of this flake's source. Absent on a dirty tree, where we
      # fall back to "dirty"; the okf binary's --version then prints
      # "okf v0.9.0.0 (dirty)".
      gitRev = inputs.self.shortRev or "dirty";

      okf-core =
        haskellPackages.callCabal2nix "okf-core" (inputs.self + "/okf-core") { };

      # nix build strips .git/, so the Template Haskell hash read in
      # Okf.Cli.Version returns Left. We inject the SHA as the CPP macro GIT_HASH
      # at configure time so the module's #ifdef GIT_HASH fallback supplies it.
      # The escaped quotes make GIT_HASH expand to a Haskell string literal.
      okf-cli = pkgs.haskell.lib.compose.overrideCabal
        (drv: {
          configureFlags = (drv.configureFlags or [ ]) ++ [
            "--ghc-option=-DGIT_HASH=\"${builtins.substring 0 7 gitRev}\""
          ];
        })
        (haskellPackages.callCabal2nix "okf-cli" (inputs.self + "/okf-cli") {
          inherit okf-core;
        });
    in
    {
      # fzf powers the interactive bundle and concept pickers in `okf show`
      # (see docs/adr/2-interactive-bundle-and-concept-selection.md). It is an
      # optional *runtime* dependency — okf builds, tests, and runs without it —
      # but shipping it in the dev shell means the pickers can be exercised
      # straight from a fresh clone.
      haskellProject.extraDevPackages = [ pkgs.fzf ];

      packages.okf-core = okf-core;
      packages.okf-cli = okf-cli;
      packages.default = okf-cli;
    };
}
