#!/usr/bin/env bash

set -euo pipefail

usage() {
  printf 'Usage: %s TAG\n' "${0##*/}" >&2
}

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi

for required_command in dhall git mktemp cp mv; do
  if ! command -v "$required_command" >/dev/null 2>&1; then
    printf 'Required command not found: %s\n' "$required_command" >&2
    exit 1
  fi
done

tag=$1
case "$tag" in
  v[0-9]*) ;;
  *)
    printf 'Expected a release tag such as v0.10.0, got: %s\n' "$tag" >&2
    exit 2
    ;;
esac

repository_url=https://github.com/shinzui/okf-profiles.git
raw_package_url="https://raw.githubusercontent.com/shinzui/okf-profiles/${tag}/package.dhall"
script_directory=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repository_root=$(cd "$script_directory/.." && pwd)
fixture_parent="$repository_root/okf-core/test/fixtures"
fixture_directory="$fixture_parent/catalogue"

mkdir -p "$fixture_parent"

checkout_root=$(mktemp -d "${TMPDIR:-/tmp}/okf-default-registry.XXXXXX")
staging_root=$(mktemp -d "$fixture_parent/.catalogue-refresh.XXXXXX")
backup_directory=

cleanup() {
  rm -rf -- "$checkout_root" "$staging_root"

  if [[ -n "$backup_directory" && -d "$backup_directory" ]]; then
    if [[ ! -e "$fixture_directory" ]]; then
      mv "$backup_directory" "$fixture_directory"
    else
      rm -rf -- "$backup_directory"
    fi
  fi
}
trap cleanup EXIT

checkout_directory="$checkout_root/okf-profiles"
git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$tag" "$repository_url" "$checkout_directory"

for required_path in package.dhall Profile profiles Profile/okf.dhall; do
  if [[ ! -e "$checkout_directory/$required_path" ]]; then
    printf 'Tag %s does not contain required path: %s\n' "$tag" "$required_path" >&2
    exit 1
  fi
done

package_hash=$(dhall hash --file "$checkout_directory/package.dhall")
if [[ ! $package_hash =~ ^sha256:[0-9a-f]{64}$ ]]; then
  printf 'dhall hash returned an unexpected value: %s\n' "$package_hash" >&2
  exit 1
fi

staged_catalogue="$staging_root/catalogue"
mkdir -p "$staged_catalogue"
cp "$checkout_directory/package.dhall" "$staged_catalogue/package.dhall"
cp -R "$checkout_directory/Profile" "$staged_catalogue/Profile"
cp -R "$checkout_directory/profiles" "$staged_catalogue/profiles"

resolved_schema="$staging_root/okf.dhall"
dhall resolve --file "$checkout_directory/Profile/okf.dhall" >"$resolved_schema"
mv "$resolved_schema" "$staged_catalogue/Profile/okf.dhall"

package_with_header="$staging_root/package.dhall"
{
  printf '%s\n' "--| Offline snapshot of mori://shinzui/okf-profiles at ${tag}."
  printf '%s\n' '-- Generated by scripts/refresh-default-registry.sh; do not edit by hand.'
  printf '%s\n' '-- Profile/okf.dhall is the resolved schema pinned by that release, so this'
  printf '%s\n' '-- fixture evaluates without network access.'
  command cat "$staged_catalogue/package.dhall"
} >"$package_with_header"
mv "$package_with_header" "$staged_catalogue/package.dhall"

if [[ -e "$fixture_directory" ]]; then
  backup_directory="$fixture_parent/.catalogue-backup.$$"
  if [[ -e "$backup_directory" ]]; then
    printf 'Refusing to overwrite backup path: %s\n' "$backup_directory" >&2
    exit 1
  fi
  mv "$fixture_directory" "$backup_directory"
fi

if ! mv "$staged_catalogue" "$fixture_directory"; then
  if [[ -n "$backup_directory" && -d "$backup_directory" ]]; then
    mv "$backup_directory" "$fixture_directory"
    backup_directory=
  fi
  exit 1
fi

if [[ -n "$backup_directory" ]]; then
  rm -rf -- "$backup_directory"
  backup_directory=
fi

printf 'Updated offline fixture: %s\n' "$fixture_directory"
printf 'defaultRegistryReference =\n'
printf '  "%s\\\n' "$raw_package_url"
printf '  \\ %s"\n' "$package_hash"
